### ISSUE TITLE
Code blocks are overflowing

### ISSUE THREAD

**Issue by ITZSHOAIB** [ITZSHOAIB/rehype-code-group#17]
<img width="503" alt="image" src="https://github.com/user-attachments/assets/29873c0c-d4d3-48f6-a9bd-b936e6854bbe">

## Problem:

In smaller devices, the code blocks are overflowing if the content is long.

## Solution:

Add `overflow-x: auto` in `rcg-block` class to fix this issue
https://github.com/ITZSHOAIB/rehype-code-group/blob/main/src/elements/styles.ts#L65-L66

**Comment by Indronil22** [comment]
https://github.com/ITZSHOAIB/rehype-code-group/pull/18
